language: java
jdk:
# JDK 8 is not supported
#  - oraclejdk8
# JDK 7 is set to deploy the docs in the configuration matrix
#  - oraclejdk7
  - openjdk7
matrix:
  include:
    # Documentation deployed with JDK7
    - jdk: oraclejdk7
      env: DEPLOY_DOCS=true
    
before_install:
  # Sets the deployment flags
  - export PULL_REQUEST=$TRAVIS_PULL_REQUEST
  # Default values for deployment flags
  - if [ -z "$DEPLOY" ]; then export DEPLOY=false; fi
  - if [ -z "$DEPLOY_DOCS" ]; then export DEPLOY_DOCS=false; fi
  # Sets the version type
  - export VERSION_TYPE=other
  - if [ "$TRAVIS_BRANCH" == "master" ]; then export VERSION_TYPE=release; fi
  - if [ "$TRAVIS_BRANCH" == "develop" ]; then export VERSION_TYPE=develop; fi
  # Scripts are set as executable
  - chmod +x ./.scripts/create-maven-settings.sh
  - chmod +x ./.scripts/deploy.sh
  - chmod +x ./.scripts/deploy-site.sh
  # Creates Maven settings
  - ./.scripts/create-maven-settings.sh
script:
  # Unit and integration tests are run
  - mvn clean verify
after_success:
  # Documentation deployment script
  - ./.scripts/deploy-site.sh
  # Code artifacts deployment script
  - ./.scripts/deploy.sh
